### ISSUE TITLE
After running Docker commands, service doesn't seem to be up

### ISSUE THREAD

**Issue by genomics-geek** [nmdp-bioinformatics/service-gfe-submission#24]
I followed the commands listed [here](https://github.com/nmdp-bioinformatics/service-gfe-submission#docker), and then visited `http://localhost:8080/` and I get no response.

**Comment by pbashyal-nmdp** [comment]
Try:
```
docker pull nmdpbioinformatics/service-gfe-submission
docker run -d --name service-gfe-submission -p 8080:5050 nmdpbioinformatics/service-gfe-submission
```

Then visit `http://localhost:8080/`

**Comment by genomics-geek** [comment]
Thanks, this has resolved our issue.
