### ISSUE TITLE
Allow GFE to accept VCF as imput

### ISSUE THREAD

**Issue by mmaiers-nmdp** [nmdp-bioinformatics/service-gfe-submission#37]
From Jill and Jurgen: make GFE accept VCF as input.  GFE would transform the VCF to 'correctly formatted fasta'

**Comment by mhalagan-nmdp** [comment]
This will have to be a new repository because it's out of the scope of this service. I started a new repository for this and it's located here:
https://github.com/mhalagan-nmdp/vcf2fa
