### ISSUE TITLE
Images for wiki

### ISSUE THREAD

**Issue by dcox-nmdp** [nmdp-bioinformatics/service-gfe-submission#39]
![download](https://user-images.githubusercontent.com/28784768/27141102-f442e706-50ec-11e7-9db4-200f07426110.png)

**Comment by mhalagan-nmdp** [comment]
I actually intended on not making a full wiki for this github page, but rather a readthedocs. This is not just geared towards developers, therefore I felt readthedocs was a better to use platform for reaching people interested in GFE. 

The documentation is available here:
http://service-gfe-submission.readthedocs.io/en/latest

I'm fine with having a wiki, but I want to make sure we direct users to the readthedocs page for more detailed information.

Thanks,
Mike Halagan

**Comment by pbashyal-nmdp** [comment]
This will be minimal enough to explain the project a bit and will point to the readthedocs for the full documentation.

**Comment by mhalagan-nmdp** [comment]
Sounds good to me.
